# Docker Compose semplificato per Open-LLM-VTuber
services:
  # Solo Redis per ora - il VTuber lo avviamo manualmente
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
